[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true




remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@aave/core-v3/=lib/aave-v3-core/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@circle/cctp/=lib/evm-cctp-contracts/src/",
    "solady/=lib/solady/src/"
]

fs_permissions = [
    { access = "read", path = "./configs" },
    { access = "read-write", path = "./deployments" }
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
